BACKBONE2D:
  YOLOv8:
    ver : m

    PRETRAIN:
      n : weights/backbone2D/YOLOv8/v8_n.pth
      s : weights/backbone2D/YOLOv8/v8_s.pth
      m : weights/backbone2D/YOLOv8/v8_m.pth
      l : weights/backbone2D/YOLOv8/v8_l.pth
      x : weights/backbone2D/YOLOv8/v8_x.pth

BACKBONE3D:

  MOBILENET:
    width_mult: 2.0

    PRETRAIN:
      width_mult_0.5x  : weights/backbone3D/mobilenet/kinetics_mobilenet_0.5x_RGB_16_best.pth
      width_mult_1.0x  : weights/backbone3D/mobilenet/kinetics_mobilenet_1.0x_RGB_16_best.pth
      width_mult_1.5x  : weights/backbone3D/mobilenet/kinetics_mobilenet_1.5x_RGB_16_best.pth
      width_mult_2.0x  : weights/backbone3D/mobilenet/kinetics_mobilenet_2.0x_RGB_16_best.pth

  MOBILENETv2:
    width_mult: 1.0

    PRETRAIN:
      width_mult_0.2x  : weights/backbone3D/mobilenetv2/kinetics_mobilenetv2_0.2x_RGB_16_best.pth
      width_mult_0.45x : weights/backbone3D/mobilenetv2/kinetics_mobilenetv2_0.45x_RGB_16_best.pth
      width_mult_0.7x  : weights/backbone3D/mobilenetv2/kinetics_mobilenetv2_0.7x_RGB_16_best.pth
      width_mult_1.0x  : weights/backbone3D/mobilenetv2/kinetics_mobilenetv2_1.0x_RGB_16_best.pth

  SHUFFLENET:
    width_mult: 2.0

    PRETRAIN:
      width_mult_0.5x  : weights/backbone3D/shufflenet/kinetics_shufflenet_0.5x_G3_RGB_16_best.pth
      width_mult_1.0x  : weights/backbone3D/shufflenet/kinetics_shufflenet_1.0x_G3_RGB_16_best.pth
      width_mult_1.5x  : weights/backbone3D/shufflenet/kinetics_shufflenet_1.5x_G3_RGB_16_best.pth
      width_mult_2.0x  : weights/backbone3D/shufflenet/kinetics_shufflenet_2.0x_G3_RGB_16_best.pth

  SHUFFLENETv2:
    width_mult: 2.0

    PRETRAIN:
      width_mult_0.25x : weights/backbone3D/shufflenetv2/kinetics_shufflenetv2_0.25x_RGB_16_best.pth
      width_mult_1.0x  : weights/backbone3D/shufflenetv2/kinetics_shufflenetv2_1.0x_RGB_16_best.pth
      width_mult_1.5x  : weights/backbone3D/shufflenetv2/kinetics_shufflenetv2_1.5x_RGB_16_best.pth
      width_mult_2.0x  : weights/backbone3D/shufflenetv2/kinetics_shufflenetv2_2.0x_RGB_16_best.pth
      
  I3D:
    PRETRAIN:
      default: weights/backbone3D/I3D/rgb_imagenet.pth
  
  RESNET:
    ver : 101

    PRETRAIN:
      ver_18 : weights/backbone3D/resnet/kinetics_resnet_18_RGB_16_best.pth
      ver_50 : weights/backbone3D/resnet/kinetics_resnet_50_RGB_16_best.pth
      ver_101: weights/backbone3D/resnet/kinetics_resnet_101_RGB_16_best.pth

  RESNEXT:
    ver : 101

    PRETRAIN:
      ver_101 : weights/backbone3D/resnext/resnext-101-kinetics.pth

LOSS:
  TAL:
    top_k  : 10
    alpha  : 0.5
    beta   : 6.0
    radius : 2.5
    soft_label : False

    scale_cls_loss : 0.5
    scale_box_loss : 7.5
    scale_dfl_loss : 1.5

  SIMOTA:
    top_k  : 10
    gamma  : 0.5
    radius : 2.5
    mode   : balance
    soft_label : True

    dynamic_k     : False
    dynamic_top_k : 40

    scale_cls_loss : 0.5
    scale_box_loss : 7.5
    scale_dfl_loss : 1.5

config_path       : utils/ucf_config.yaml
dataset           : ucf
loss              : tal
active_checker    : True
num_classes       : 2
backbone2D        : yolov8
backbone3D        : shufflenetv2
fusion_module     : CFAM
mode              : decoupled
interchannels     : [192, 192, 192]
pretrain_path     : ema_epoch_7.pth
data_root         : /path/to/your/main_dataset_folder
img_size          : [384, 640] # (Height, Width). Always use List
clip_length       : 5
num_workers       : 20
batch_size        : 20
acc_grad          : 16
lr                : 0.0001
weight_decay      : 0.0005
max_step_warmup   : 700
adjustlr_schedule : [1, 2, 3, 4, 5]
max_epoch         : 100
lr_decay          : 0.5
save_folder       : weights/model_checkpoint
sampling_rate     : 7

idx2name:
  0 : fight
  1 : falldown
  # .....

augment:
  # GEOMETRIC TRANSFORMS
  geometric:  
    # Random Resized Crop
    random_resized_crop: 0.5  # probability
    horizontal_flip: 0.5 # Horizontal Flip
    affine: 0.4 # Affine Transform (scale, translate, shear)
    perspective: 0.05 # Perspective Transform

  # COLOR TRANSFORMS
  color:
    hsv: 0.5 # HSV Augmentation
    brightness_contrast: 0.5 # Brightness & Contrast
    color_jitter: 0.1 # Color Jitter
    rgb_shift: 0.1 # RGB Channel Shift

  # NOISE & BLUR
  noise_blur:
    blur: 0.2 # Blur (choose type randomly when applied)
    gaussian_noise: 0.2 # Gaussian Noise

  # WEATHER EFFECTS
  weather: 0.1  # overall probability for any weather effect

  # QUALITY DEGRADATION
  quality:
    jpeg_compression: 0.0 # JPEG Compression
    downscale_upscale: 0.0 # Downscale-Upscale (simulate low resolution)

  # PIXEL-LEVEL TRANSFORMS
  pixel:
    coarse_dropout: 0.0 # Coarse Dropout (Random Cutout)
  
  # Filtering and blanking
  filtering:
    wh_thr: 10 # Minimum requirement to width/height in pixels of a box (default: 10)
    ar_thr: 20 # Maximum aspect ratio  (default: 20)
    area_thr: 0.1 # Minimum area retention ratio (default: 0.1)
